name: ci development

on: 
  pull_request:
    branches:
      - main 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 16.20.2
        cache: 'yarn'

    - name: Install dependencies
      run: yarn install
    
    - name: Build project
      run: yarn build

    - name: Linting
      run: yarn lint

    - name: Run Jest Tests
      run: yarn test
    
