name: ci development

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Linting
        run: yarn run lint

      - name: Testing
        run: yarn run test:ci

      - name: Build
        run: yarn run build
